export { default as Startup } from './Startup/Index'
export { default as LoginScreen } from './Login/Index'
export { default as SignUpScreen } from './SignUp/Index'
export { default as MainScreen } from './MainScreen/Index'
export { default as Scanner } from './Scanner/Index'
export { default as Forgot } from './Forgot/Index'
export { default as TestResult } from './TestResult/Index'
export { default as TestPhoto } from './TestPhoto/Index'
export { default as ResultPreview } from './ResultPreview/Index'
export { default as PhotoPreview } from './PhotoPreview/Index'
export { default as Certificate } from './Certificate/Index'
export { default as CommonWebView } from './CommonWebView/index'
export { default as PhotoIdPreview } from './PhotoIdPreview/Index'
export {default as EmailVerification } from './EmailVerification/Index'
export { default as ResetPassword } from './ResetPassword/Index';
export { default as Records } from './Records/Index';
export { default as RecordDetail } from './RecordDetail/Index';
export { default as SettingsAccount } from './SettingsAccount/Index'
export { default as Language } from './Language/Index'
